### ISSUE TITLE
Unable to establish phoenix channel websocket connection 501

### ISSUE THREAD

**Issue by mbuhot** [GoogleCloudPlatform/elixir-runtime#12]
I've created a fairly trivial chat application using phoenix channels.
It is deployed to https://chatter-193110.appspot.com
Running locally, I'm able to connect from multiple hosts on my local network.
However once deployed to gcloud, I get websocket connection errors:

```
app-206e4dc53bfa5121d23ba99ca788f34c.js?vsn=d:1 WebSocket connection to 'wss://chatter-193110.appspot.com/socket/websocket?token=undefined&vsn=2.0.0' failed: Error during WebSocket handshake: Unexpected response code: 501
```

Help appreciated!

**Comment by dazuma** [comment]
Websockets don't currently play well with App Engine. It's a known issue, and I have it on good authority that it's being worked on, but it's not there yet.

**Comment by mbuhot** [comment]
> It's a known issue

Maybe worth putting a note about this in the documentation. 

Maybe it can be worked around using the LongPoll transport for channels.

**Comment by dazuma** [comment]
Good idea, this should be documented. I'll leave this open to update the docs and the tutorial. And yes, I believe long-poll should still work.

**Comment by zeroasterisk** [comment]
@mbuhot would you mind confirming that this issue is resolved?

**Comment by mbuhot** [comment]
@zeroaaterisk sorry I no longer have a GCP account.

**Comment by carlodicelico** [comment]
@zeroasterisk, I can confirm that websockets work in GAE Flex for you:

<img width="967" alt="Screen_Shot_2019-04-07_at_12_08_27" src="https://user-images.githubusercontent.com/1778532/55686365-57ec9180-592e-11e9-8f42-0b7fa3635056.png">

<img width="897" alt="Screen Shot 2019-04-07 at 12 08 42" src="https://user-images.githubusercontent.com/1778532/55686337-f3313700-592d-11e9-95aa-690fcdc1a431.png">

I'm using Phoenix 1.4.3 deployed with the latest Elixir runtime.

**Comment by dbradleyfl** [comment]
I've found that I can't connect to my phoenix app's websocket (channel) using the custom domain I setup. I can only connect to the websocket using the appspot url. Is that the case for everyone else?
