### ISSUE TITLE
gcloud app deploy fails

### ISSUE THREAD

**Issue by dtrce** [GoogleCloudPlatform/elixir-runtime#13]
<img width="1197" alt="screenshot 2018-01-27 00 09 53" src="https://user-images.githubusercontent.com/838519/35468892-76952758-02f6-11e8-833c-07d80578142b.png">

**Comment by dazuma** [comment]
It looks like your app name is `:rising_chain` but your `app.yaml` file says `  release_app: risingchain` (missing the underscore)

**Comment by dtrce** [comment]
That did the trick. Deploy did go further than last time but it eventually failed with the following error:


Updating service [default] (this may take several minutes)...failed.
ERROR: (gcloud.app.deploy) Error Response: [9]
Application startup error:
/bin/sh: 1: exec: mix: not found

**Comment by dtrce** [comment]
thanks that worked!
