### ISSUE TITLE
Deploying app is hanging for ever

### ISSUE THREAD

**Issue by mustela** [GoogleCloudPlatform/elixir-runtime#24]
Hi there! Not sure if this is an issue I should post here, but as far as I see it's connected to the elixir runtime. 

Deploying the app never ends, it just hangs for ever in the uploading step

```
DEBUG: No bucket specified, retrieving default bucket.
DEBUG: Using bucket [gs://staging.testing-246310.appspot.com].
DEBUG: Service [appengineflex.googleapis.com] is already enabled for project [testing-246310]
Beginning deployment of service [default]...
INFO: Using ignore file at [/ny-site/.gcloudignore].
DEBUG: Skipping file [test]
DEBUG: Skipping file [_build]
DEBUG: Skipping file [deps]
INFO: Need Dockerfile to be generated for runtime gs://elixir-runtime/elixir.yaml
Building and pushing image for service [default]
INFO: Uploading [/var/folders/vj/ks36k0t95k599byfwbmwym3w0000gn/T/tmpUD0bZd/src.tgz] to [staging.testing-246310.appspot.com/us.gcr.io/testing-246310/appengine/default.20190711t004847:latest]
```

I have tried to deploy other apps/configs and everything seems to be working except when I try to deploy an app with the elixir runtime.

Any clue about what could be causing the issue?

Thanks!

**Comment by dazuma** [comment]
If it appears to hang while uploading, it's possible it's just an enormous upload. For Elixir apps, I've noticed the `assets/node_modules` directory is a common culprit. It's gigantic, and it doesn't need to be uploaded to App Engine—the runtime will do its own `npm install` if needed during its build process. So try adding it to your `.gcloudignore`.

**Comment by mustela** [comment]
@dazuma I found the issue, it was deliver releases. I had like 30 releases in there and around 2gb... removing those fixed the problem. 

Thanks
