### ISSUE TITLE
Support for Phoenix 1.2

### ISSUE THREAD

**Issue by newterminator** [GoogleCloudPlatform/elixir-runtime#5]
I have got 2 apps that I'd like to deploy to GAP Flexible Environment. 

Is it possible to do so for apps written using Phoenix 1.2 ?

**Comment by dazuma** [comment]
Yes, Phoenix 1.2 is supported.

**Comment by dazuma** [comment]
See https://cloud.google.com/community/tutorials/elixir-phoenix-on-google-app-engine for some howtos.

**Comment by newterminator** [comment]
Hey @dazuma Thanks for your quick response. I am gonna check out the tutorial and get started with it today !!!
Thanks so much.
